In [1]:
#######################
# BANK CHURN PREDICTION
#######################
# import libraries
# pandas for data handling
# numpy for numerical operations
# matplotlib and seaborn for visualization
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from IPython.display import display

# ML utilities
# split data, hyperparameter tuning
# feature scaling
# chain pre-processing
# performance evaluation
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report, roc_auc_score

# machine learning models for comparison
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

In [2]:
########
# DATA
########

# Define categorical columns
CATEGORICAL_COLS = [
    'Gender', 'Education_Level', 'Marital_Status',
    'Income_Category', 'Card_Category'
]

# Data load
def load_data(path):
    
    # If the file cannot be found in the location I specified, display the message below, easy fix
    if not os.path.exists(path):
        raise FileNotFoundError(f"Data file not found: {path}")

    # Read the file using the path provided
    df = pd.read_csv(path)
    
    # Drop first (Client Number) and last two columns (existing NB predictions so they will not be used as predictors)
    df = df.iloc[:, 1:-2]
    
    # The dependent variable is Attrition_Flag
    df['Attrition_Flag'] = df['Attrition_Flag'].map({
        'Existing Customer': 0,
        'Attrited Customer': 1
    })
    
    # One-hot encode categorical columns
    df = pd.get_dummies(df, columns=CATEGORICAL_COLS, drop_first=True)
    
    return df

# Some analytics - creating tables to see the distribution of attrition within variables
def run_eda_tables(df):
    
    tables = {}

    # Specify overall attrition
    # df['Attrition_Flag'] selects my target column, where 0 = Existing Customer and 1 = Attrited Customer
    # value_counts(normalize=True) counts how many of each value there are and normalizes it, i.e., returns proportions
    # Multiplying by 100 converts the proportions into percentages.
    overall = df['Attrition_Flag'].value_counts(normalize=True) * 100
    # pd.DataFrame(overall) converts the series into a data frame
    # .T transposes it so that the segments or buckets become rows, and the two categories (0 and 1) become columns
    # .rename(columns={0: 'Existing (%)', 1: 'Attrited (%)'}) gives meaningful column names instead of just 0 and 1
    overall_table = pd.DataFrame(overall).T.rename(columns={0: 'Existing (%)', 1: 'Attrited (%)'})
    # store the table in the tables dictionary with key 'Overall'.
    # .round(2) rounds percentages to 4 decimal places (most people like 2, I like 4...)
    tables['Overall'] = overall_table.round(4)

    # categorical variables
    # loop through each column in CATEGORICAL_COLS, calculate attrition percentages for each segment or bucket
    # the if statement checks to see if the column exists in the data frame I created above
    # pd.crosstab(df[col], df['Attrition_Flag']) creates a table showing counts of each attrition flag for 
        # every category in col
    # normalize='index' converts counts into percentages row-wise and the values sum to 100%.
    for col in CATEGORICAL_COLS:
        if col in df.columns:
            table = pd.crosstab(df[col], df['Attrition_Flag'], normalize='index') * 100
            tables[col] = table.rename(columns={0: 'Existing (%)', 1: 'Attrited (%)'}).round(2)

    # Numeric variables
    # df.select_dtypes(include=[np.number]) selects all columns with numeric data types 
    # .columns returns just the column names of numeric columns
    # the second line remove Attrition_Flag from the list of numeric columns (this is the target)
    numeric_cols = df.select_dtypes(include=[np.number]).columns
    numeric_cols = [col for col in numeric_cols if col != 'Attrition_Flag']

    # Loop through each numeric columns prepared above
    # the goal is to create binned categories for each colums
    
    for col in numeric_cols:
        try:
            # pd.qcut(df[col], q=10) divides the numeric column into 10 quantiles 
            # duplicates='drop' handles cases where some quantile edges are identical (e.g., column has few unique values
            df[f'{col}_bin'] = pd.qcut(df[col], q=10, duplicates='drop')
            # If qcut fails because there are too few unique values to split into 10 quantiles, it falls back to pd.cut
            # pd.cut(df[col], bins=5) divides the numeric column into 5 equal-width bins instead
        except ValueError:  # fallback for few unique values
            df[f'{col}_bin'] = pd.cut(df[col], bins=5)
        
        # Create a cross-tabulation table of segment or bins vs. attrition.
        # normalize='index' converts counts to percentages so each bin shows the proportion of existing vs. attrited 
        # Multiplying by 100 converts proportions to percentages.
        table = pd.crosstab(df[f'{col}_bin'], df['Attrition_Flag'], normalize='index') * 100
        # Rename columns 0 to 'Existing (%)' and 1 to 'Attrited (%)'
        # Rounds percentages to 4 decimal places.
        # Store the result in the tables dictionary under the key of the numeric column name
        tables[col] = table.rename(columns={0: 'Existing (%)', 1: 'Attrited (%)'}).round(4)
        # Remove the temporary bin column from the data frame to keep it clean
        df.drop(columns=f'{col}_bin', inplace=True)

    return tables


#############
# MAIN - Data
#############
def main(path):
    
    # load the input file, drop unnecessary columns, convert Attrition_Flag to 0,1, convert categorical variables
    df = load_data(path)
    # run the function created earlier
    attrition_tables = run_eda_tables(df)

    # Display tables in Jupyter
    for var, table in attrition_tables.items():
        print(f"\n--- {var} ---")
        display(table)
    
    # return tao things - df (data frame for modeling), dictionary of tables generated by run_eda_tables
    return df, attrition_tables


# Run the main workflow automatically from my personal projects folder
df, attrition_tables = main("C:/Users/eaffu/Documents/Personal_Projects/BankChurners.csv")

--- Overall ---

Attrition_Flag  Existing (%)  Attrited (%)
proportion            83.934        16.066

--- Customer_Age ---

Attrition_Flag    Existing (%)  Attrited (%)
Customer_Age_bin
(25.999, 36.0]         87.1930       12.8070
(36.0, 39.0]           85.2679       14.7321
(39.0, 42.0]           82.6758       17.3242
(42.0, 44.0]           82.6310       17.3690
(44.0, 46.0]           83.5041       16.4959
(46.0, 48.0]           83.0705       16.9295
(48.0, 51.0]           84.5353       15.4647
(51.0, 53.0]           84.6658       15.3342
(53.0, 57.0]           81.6993       18.3007
(57.0, 73.0]           84.0426       15.9574

--- Dependent_count ---

Attrition_Flag       Existing (%)  Attrited (%)
Dependent_count_bin
(-0.001, 1.0]             85.2662       14.7338
(1.0, 2.0]                84.2938       15.7062
(2.0, 3.0]                82.3572       17.6428
(3.0, 4.0]                83.4816       16.5184
(4.0, 5.0]                84.9057       15.0943

--- Months_on_book ---

Attrition_Flag      Existing (%)  Attrited (%)
Months_on_book_bin
(12.999, 26.0]           84.8915       15.1085
(26.0, 30.0]             84.5401       15.4599
(30.0, 33.0]             86.1842       13.8158
(33.0, 36.0]             83.0195       16.9805
(36.0, 39.0]             82.5048       17.4952
(39.0, 42.0]             85.3496       14.6504
(42.0, 46.0]             83.4951       16.5049
(46.0, 56.0]             83.6032       16.3968

--- Total_Relationship_Count ---

Attrition_Flag                Existing (%)  Attrited (%)
Total_Relationship_Count_bin
(0.999, 2.0]                       73.1073       26.8927
(2.0, 3.0]                         82.6464       17.3536
(3.0, 4.0]                         88.2322       11.7678
(4.0, 5.0]                         87.9958       12.0042
(5.0, 6.0]                         89.4962       10.5038

--- Months_Inactive_12_mon ---

Attrition_Flag              Existing (%)  Attrited (%)
Months_Inactive_12_mon_bin
(-0.001, 1.0]                    94.9160        5.0840
(1.0, 2.0]                       84.6130       15.3870
(2.0, 3.0]                       78.5231       21.4769
(3.0, 6.0]                       75.4410       24.5590

--- Contacts_Count_12_mon ---

Attrition_Flag             Existing (%)  Attrited (%)
Contacts_Count_12_mon_bin
(-0.001, 1.0]                   93.9410        6.0590
(1.0, 2.0]                      87.5116       12.4884
(2.0, 3.0]                      79.8521       20.1479
(3.0, 4.0]                      77.3707       22.6293
(4.0, 6.0]                      50.8696       49.1304

--- Credit_Limit ---

Attrition_Flag      Existing (%)  Attrited (%)
Credit_Limit_bin
(1438.299, 1762.0]       71.1045       28.8955
(1762.0, 2307.2]         83.6957       16.3043
(2307.2, 2787.0]         90.6312        9.3688
(2787.0, 3398.4]         87.5371       12.4629
(3398.4, 4549.0]         81.0837       18.9163
(4549.0, 6279.2]         84.7525       15.2475
(6279.2, 9078.4]         84.2053       15.7947
(9078.4, 13562.6]        85.1779       14.8221
(13562.6, 23400.2]       87.0681       12.9319
(23400.2, 34516.0]       84.1066       15.8934

--- Total_Revolving_Bal ---

Attrition_Flag           Existing (%)  Attrited (%)
Total_Revolving_Bal_bin
(-0.001, 748.0]               64.6923       35.3077
(748.0, 1037.4]               90.2174        9.7826
(1037.4, 1276.0]              95.6565        4.3435
(1276.0, 1482.0]              95.5752        4.4248
(1482.0, 1673.2]              95.9325        4.0675
(1673.2, 1903.0]              95.0690        4.9310
(1903.0, 2228.4]              94.6588        5.3412
(2228.4, 2517.0]              78.1836       21.8164

--- Avg_Open_To_Buy ---

Attrition_Flag       Existing (%)  Attrited (%)
Avg_Open_To_Buy_bin
(2.999, 683.0]            86.8369       13.1631
(683.0, 1026.0]           95.2475        4.7525
(1026.0, 1464.4]          82.6733       17.3267
(1464.4, 2225.0]          73.7931       26.2069
(2225.0, 3474.0]          81.3056       18.6944
(3474.0, 5195.0]          82.3297       17.6703
(5195.0, 7884.6]          83.7945       16.2055
(7884.6, 12419.8]         83.0040       16.9960
(12419.8, 21964.6]        86.9694       13.0306
(21964.6, 34516.0]        83.4156       16.5844

--- Total_Amt_Chng_Q4_Q1 ---

Attrition_Flag            Existing (%)  Attrited (%)
Total_Amt_Chng_Q4_Q1_bin
(-0.001, 0.531]                62.9775       37.0225
(0.531, 0.604]                 82.7723       17.2277
(0.604, 0.655]                 86.3148       13.6852
(0.655, 0.697]                 88.9881       11.0119
(0.697, 0.736]                 86.4271       13.5729
(0.736, 0.781]                 89.5508       10.4492
(0.781, 0.83]                  89.5314       10.4686
(0.83, 0.892]                  83.6114       16.3886
(0.892, 0.997]                 83.5657       16.4343
(0.997, 3.397]                 85.7848       14.2152

--- Total_Trans_Amt ---

Attrition_Flag       Existing (%)  Attrited (%)
Total_Trans_Amt_bin
(509.999, 1501.0]         78.1065       21.8935
(1501.0, 1914.0]          81.1451       18.8549
(1914.0, 2411.0]          52.9644       47.0356
(2411.0, 3192.4]          59.1897       40.8103
(3192.4, 3899.0]          98.7167        1.2833
(3899.0, 4267.0]          99.6055        0.3945
(4267.0, 4572.0]          99.5059        0.4941
(4572.0, 4926.0]          96.0513        3.9487
(4926.0, 8212.4]          86.6469       13.3531
(8212.4, 18484.0]         87.3643       12.6357

--- Total_Trans_Ct ---

Attrition_Flag      Existing (%)  Attrited (%)
Total_Trans_Ct_bin
(9.999, 33.0]            73.3792       26.6208
(33.0, 41.0]             61.5312       38.4688
(41.0, 50.0]             51.6160       48.3840
(50.0, 61.0]             79.0743       20.9257
(61.0, 67.0]             91.8580        8.1420
(67.0, 73.0]             94.6381        5.3619
(73.0, 78.0]             95.5010        4.4990
(78.0, 83.0]             97.8632        2.1368
(83.0, 92.0]             97.9654        2.0346
(92.0, 139.0]            99.8988        0.1012

--- Total_Ct_Chng_Q4_Q1 ---

Attrition_Flag           Existing (%)  Attrited (%)
Total_Ct_Chng_Q4_Q1_bin
(-0.001, 0.452]               43.9842       56.0158
(0.452, 0.545]                71.7092       28.2908
(0.545, 0.609]                81.3477       18.6523
(0.609, 0.657]                88.1474       11.8526
(0.657, 0.702]                92.7308        7.2692
(0.702, 0.745]                91.9052        8.0948
(0.745, 0.791]                91.8408        8.1592
(0.791, 0.853]                92.0949        7.9051
(0.853, 0.95]                 92.9703        7.0297
(0.95, 3.714]                 92.8642        7.1358

--- Avg_Utilization_Ratio ---

Attrition_Flag             Existing (%)  Attrited (%)
Avg_Utilization_Ratio_bin
(-0.001, 0.051]                 67.5658       32.4342
(0.051, 0.1]                    91.8065        8.1935
(0.1, 0.176]                    90.5605        9.4395
(0.176, 0.277]                  90.5660        9.4340
(0.277, 0.43]                   89.4995       10.5005
(0.43, 0.573]                   93.5388        6.4612
(0.573, 0.707]                  93.9783        6.0217
(0.707, 0.999]                  86.7589       13.2411

In [ ]:
#############
# SPLIT DATA
#############
# split the data into features (X) and target (y)
# axes=1 makes sure that a column is dropped and not a row
# test_size=0.2 means that 20% of the data is used for testing, 80% is used for training
# random_state=42 ensures reproducibility. Every time I run this code, I will get the same split
# stratify=y ensures that the proportion of attrited vs existing customers is the same in both training and test sets
# X_train = features for training
# X_test = features for testing
# y_train = target for training
# y_test = target for testing
def split_data(df):
    X = df.drop('Attrition_Flag', axis=1)
    y = df['Attrition_Flag']
    return train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

#####################
# TRAIN THE ML MODELS
#####################
# name = the name of the model
# model = the machine learning model object
# param_grid = dictionary of hyperparameters to search over using GridSearchCV
# scale = whether to apply StandardScaler to scale features
def train_model(name, model, param_grid, X_train, y_train, X_test, y_test, scale=True):
    print(f"\nTraining: {name}")
    
    # steps, hold the sequence of transformations and the model for a Pipeline
    # pipeline, allows one to combine preprocessing and model training in one object, everything happens in the correct order.
    # StandardScaler standardizes numeric features to have mean = 0 and st dev = 1
    # add ML model to the pipeline
    steps = []
    if scale:
        steps.append(('scaler', StandardScaler()))
    steps.append(('model', model))
    
    # Pipeline chains together multiple steps into one object
    # GridSearchCV automates hyperparameter tuning
    # cv is cross validation, I set it to 5
    # grid.fit trains the pipeline for all hyperparameter combinations using the training data 
    pipeline = Pipeline(steps)
    grid = GridSearchCV(pipeline, param_grid, cv=5, scoring='accuracy')
    grid.fit(X_train, y_train)
    
    # grid.best_estimator_ gives the pipeline that performed best during cross validation
    # predict() generates predictions for the features in the text sample
    best_model = grid.best_estimator_
    y_pred = best_model.predict(X_test)
    
    # hasattr checks whether the model has a predict_proba method
    
    # predict_proba(X_test) returns probabilities of 0 and 1 
    # [:,1] selects only the probability of attrition   
    # if the model doesn’t have predict_proba, it cannot calculate probabilities, use y_pred as proxy
    # In that case, we just use the predicted class labels (y_pred) as a proxy.
    if hasattr(best_model.named_steps['model'], "predict_proba"):
        y_prob = best_model.predict_proba(X_test)[:,1]
    else:
        y_prob = y_pred
    
    print("Best Params:", grid.best_params_)
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("ROC-AUC:", roc_auc_score(y_test, y_prob))
    print(classification_report(y_test, y_pred))
    
    return best_model

# define all ML models to be trained - model object, hyperparameters, whether feature scaling is required
def get_models():
       return {
        "Logistic Regression": {
            "model": LogisticRegression(max_iter=1000, class_weight='balanced'),
            "params": {"model__C": [0.01, 0.1, 1, 10]},
            "scale": True  # scaling needed for linear models
        },

        "Decision Tree": {
            "model": DecisionTreeClassifier(),
            "params": {
                "model__max_depth": [3, 5, 10, None],
                "model__min_samples_split": [2, 5, 10]
            },
            "scale": False  # trees do not need scaling
        },

        "Random Forest": {
            "model": RandomForestClassifier(class_weight='balanced'),
            "params": {
                "model__n_estimators": [100, 200],
                "model__max_depth": [5, 10, None]
            },
            "scale": False
        },

        "Gradient Boosting": {
            "model": GradientBoostingClassifier(),
            "params": {
                "model__n_estimators": [100, 200],
                "model__learning_rate": [0.01, 0.1],
                "model__max_depth": [3, 5]
            },
            "scale": False
        },

        "AdaBoost": {
            "model": AdaBoostClassifier(),
            "params": {
                "model__n_estimators": [50, 100],
                "model__learning_rate": [0.01, 0.1, 1]
            },
            "scale": False
        },

        "SVM": {
            "model": SVC(probability=True),
            "params": {
                "model__C": [0.1, 1, 10],
                "model__kernel": ["rbf", "linear"]
            },
            "scale": True
        },

        "KNN": {
            "model": KNeighborsClassifier(),
            "params": {
                "model__n_neighbors": [3, 5, 7],
                "model__weights": ["uniform", "distance"]
            },
            "scale": True
        },

        "Naive Bayes": {
            "model": GaussianNB(),
            "params": {"model__var_smoothing": [1e-9, 1e-8, 1e-7]},
            "scale": False
        }
    }

def run_all_models(models, X_train, y_train, X_test, y_test):
    results = []
    trained_models = {}
    for name, config in models.items():
        model = train_model(name, config["model"], config["params"], X_train, y_train, X_test, y_test, scale=config["scale"])
        trained_models[name] = model
        y_pred = model.predict(X_test)
        acc = accuracy_score(y_test, y_pred)
        results.append((name, acc))
    results_df = pd.DataFrame(results, columns=['Model','Accuracy']).sort_values(by='Accuracy', ascending=False)
    return trained_models, results_df

################
# MAIN - MODELS
################
# Input data path
path = "C:/Users/eaffu/Documents/Personal_Projects/BankChurners.csv"

# Load data
df = load_data(path)

# Split data
X_train, X_test, y_train, y_test = split_data(df)

# Train models and compare
models = get_models()
trained_models, results_df = run_all_models(models, X_train, y_train, X_test, y_test)

print("\nModel Comparison:")
display(results_df)

Training: Logistic Regression
Best Params: {'model__C': 0.1}
Accuracy: 0.8558736426456071
ROC-AUC: 0.9196581196581196
              precision    recall  f1-score   support

           0       0.96      0.86      0.91      1701
           1       0.53      0.82      0.65       325

    accuracy                           0.86      2026
   macro avg       0.75      0.84      0.78      2026
weighted avg       0.89      0.86      0.87      2026


Training: Decision Tree
Best Params: {'model__max_depth': 10, 'model__min_samples_split': 5}
Accuracy: 0.9437314906219151
ROC-AUC: 0.9205209605209603
              precision    recall  f1-score   support

           0       0.96      0.97      0.97      1701
           1       0.84      0.80      0.82       325

    accuracy                           0.94      2026
   macro avg       0.90      0.88      0.89      2026
weighted avg       0.94      0.94      0.94      2026


Training: Random Forest
Best Params: {'model__max_depth': 10, 'model__n_estimators': 200}
Accuracy: 0.947680157946693
ROC-AUC: 0.9804893049337494
              precision    recall  f1-score   support

           0       0.97      0.97      0.97      1701
           1       0.84      0.83      0.84       325

    accuracy                           0.95      2026
   macro avg       0.91      0.90      0.90      2026
weighted avg       0.95      0.95      0.95      2026


Training: Gradient Boosting